### PR TITLE
Switch to using PowerShellStandard.Library to allow a single cross-platform binary

### PR DESCRIPTION
**Pull request by Jaykul**
Addresses #104

I haven't looked at how you put the actual module together -- this only addresses compilation...

### CODE REVIEW

**Comment by Jaykul** [comment]
Also, the build will "fail" because there's only a "Core" build now, no separate "Desktop" build is required or desired.

**Comment by jianyunt** [comment]
@Jaykul I updated build, setup, and test scripts. Now we passed all checks. Please review the changes.  BTW, thanks for your contriubtions. really appreciated.

**Comment by jianyunt** [comment]
@stefanstranger, @jzabroski @Chaganti @dfinke @johnzabroski @DexterPOSH, @ravikanth, once we checkin this PR,  SHiPS will depends on .net 4.7.1 on Windows desktop. Any concerns if we go for it?

cc @edyoung @HemantMahawar

**Comment by jzabroski** [comment]
Hmm... does PowerShell allow assembly redirects?

I just woke up and am not sure why it can't target 4.6.x ...

That said, I think it is a great idea to ask lots of downstream consumers if they're impacted. Simply put, I am not.

**Comment by jzabroski** [comment]
One other comment. [PSModuleInfo](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psmoduleinfo?view=powershellsdk-1.1.0) has a [DotNetFraneworkVersion](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.psmoduleinfo.dotnetframeworkversion?view=powershellsdk-1.1.0#System_Management_Automation_PSModuleInfo_DotNetFrameworkVersion), that was [introduced in PowerShell 3.0](https://msdn.microsoft.com/en-us/library/system.management.automation.psmoduleinfo_members(v=vs.85).aspx#Public Properties). I'm on my mobile phone so reviewing code is hard but the psm1 should be updated with new version number to indicate this.

**Comment by jianyunt** [comment]
@jzabroski about a year, .Net team announced [.net framework 4.7.1 release](https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/). It supports downlevel OSs to Win7.  Also the .Net 4.7.1 has builtin support for .NET Standard 2.0. 

We can think of the .NET standard as "abstract layer" of .net 4.7.1 and .net core. For project like SHiPS if we compile against the .Net standard, its library will run on both .net core and .net full (here .Net 4.7.1) - cross platform support.  You can also see more info in the issue https://github.com/PowerShell/SHiPS/issues/104.

**Comment by jzabroski** [comment]
@jianyunt  I'm aware. I'm a 10 years experience .NET engineer. I'm merely explicitly calling out the need to reference the dependencies, otherwise the package manager can't do its' job of protecting developers from pulling in bad dependencies.

The PowerShell Module Manifest is documented in many places.  A quick google search found this tutorial: [How to Write a Module Manifest](https://msdn.microsoft.com/en-us/abe4c24b-e64e-4a61-81d5-18c4fceba0b6). In the tutorial, you can clearly see a manifest _should_ take a **DotNetFrameworkVersion key**.

**Comment by jzabroski** [comment]
@Jaykul  can you please update https://github.com/PowerShell/SHiPS/blob/development/src/Modules/SHiPS.psd1 to take the DotNetFrameworkVersion key 4.7.1

**Comment by Jaykul** [comment]
Note: I haven't _truly_ tested this with .NET 4.6.1 but it *should* work, [based on version notes](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) and the [table here](https://github.com/dotnet/standard/blob/master/docs/versions.md)

**Comment by jianyunt** [comment]
@jzabroski,  I added  DotNetFrameworkVersion in SHiPS.psd1. Thanks.

**Comment by jianyunt** [comment]
@Jaykul we need 4.7.1 because 4.6.1 doesn't come with the .Net standard shims, only 4.7.1 includes those.  This means that if we target .Net Std2.0 and 4.6.1 we also need to ship netstandard.dll. Or users need to install the .net combability pack. To avoid this hassle, I updated it to 4.7.1.

**Comment by jzabroski** [comment]
I saw. :) thanks!

**Pull request merged**
