### PR TITLE
(GH-103) Convert all text encoding to UTF8 without BOM

### LINKED ISSUE #103: File encoding is wildly divergent
The source files in the repository use a combination of UTF8, UTF8 BOM, UTF16LE file encodings.   In my opinion they should all be the same, unless there are technical reasons to the contrary.  Would it possible to make them all UTF8 (no BOM)?

### PR DESCRIPTION
**Pull request by glennsarti**
Fixes #103 

Previously the source files had wildly divergent text encodings, including
UTF16 which git sees as a binary file. This commit converts all text files to
UTF8 without BOM to standardise on a cross platform text file encoding format.

### CODE REVIEW

**Comment by jianyunt** [comment]
The building is failing because the key file .snk file is modified. Please revert the change to the .snk file.
In addition, you may not change .png file either because it may not display properly after the change.
@glennsarti thank you for your contributions the SHiPS!

**Comment by glennsarti** [comment]
Whoopsy.  Was a bit overzealous there...fixed and rebased.

**Comment by jianyunt** [comment]
Thanks. test on Windows desktop is failing, it looks like something to do with the encoding.

**Comment by glennsarti** [comment]
There were some hidden whitespace characters and emdash causing issues.  Also modified the UTF16 files so they now appear as text files not binary.

**Comment by jianyunt** [comment]
Thanks, glennsarti!

**Pull request merged**
